"""add leave and calendar tables

Revision ID: 0183d5336c90
Revises: 60d5c1c8f1e8
Create Date: 2026-07-21 15:04:41.113151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0183d5336c90'
down_revision: Union[str, Sequence[str], None] = '60d5c1c8f1e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_company_events_event_id'), 'company_events', ['event_id'], unique=False)
    op.create_table('holidays',
    sa.Column('holiday_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('holiday_id')
    )
    op.create_index(op.f('ix_holidays_holiday_id'), 'holidays', ['holiday_id'], unique=False)
    op.create_table('leave_types',
    sa.Column('leave_type_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('accrual_method', sa.String(), nullable=False),
    sa.Column('carry_forward_limit', sa.Integer(), nullable=False),
    sa.Column('doc_required_threshold', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('leave_type_id')
    )
    op.create_index(op.f('ix_leave_types_leave_type_id'), 'leave_types', ['leave_type_id'], unique=False)
    op.create_table('leave_applications',
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('leave_type_id', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='leavestatus'), nullable=False),
    sa.Column('approver_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.leave_type_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_index(op.f('ix_leave_applications_application_id'), 'leave_applications', ['application_id'], unique=False)
    op.create_table('leave_balances',
    sa.Column('balance_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('leave_type_id', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.leave_type_id'], ),
    sa.PrimaryKeyConstraint('balance_id')
    )
    op.create_index(op.f('ix_leave_balances_balance_id'), 'leave_balances', ['balance_id'], unique=False)
    op.create_table('leave_audit_logs',
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['leave_applications.application_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_leave_audit_logs_log_id'), 'leave_audit_logs', ['log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leave_audit_logs_log_id'), table_name='leave_audit_logs')
    op.drop_table('leave_audit_logs')
    op.drop_index(op.f('ix_leave_balances_balance_id'), table_name='leave_balances')
    op.drop_table('leave_balances')
    op.drop_index(op.f('ix_leave_applications_application_id'), table_name='leave_applications')
    op.drop_table('leave_applications')
    op.drop_index(op.f('ix_leave_types_leave_type_id'), table_name='leave_types')
    op.drop_table('leave_types')
    op.drop_index(op.f('ix_holidays_holiday_id'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_company_events_event_id'), table_name='company_events')
    op.drop_table('company_events')
    # ### end Alembic commands ###
