"""announcements

Revision ID: 2b69782b7c4c
Revises: 4bb1f85e63cb
Create Date: 2026-07-14 11:21:31.242693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b69782b7c4c'
down_revision: Union[str, Sequence[str], None] = '4bb1f85e63cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('announcement_acks', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_announcement_acks_id'), 'announcement_acks', ['id'], unique=False)
    op.add_column('announcements', sa.Column('target_value', sa.String(), nullable=True))
    op.add_column('announcements', sa.Column('requires_ack', sa.Boolean(), nullable=False))
    op.add_column('announcements', sa.Column('status', sa.String(), nullable=False))
    op.add_column('announcements', sa.Column('posted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.drop_column('announcements', 'target_team_id')
    op.drop_column('announcements', 'requires_acknowledgment')
    op.drop_column('announcements', 'created_at')
    op.drop_column('announcements', 'is_archived')
    op.drop_column('announcements', 'target_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('target_role', sa.VARCHAR(), nullable=True))
    op.add_column('announcements', sa.Column('is_archived', sa.BOOLEAN(), nullable=False))
    op.add_column('announcements', sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('announcements', sa.Column('requires_acknowledgment', sa.BOOLEAN(), nullable=False))
    op.add_column('announcements', sa.Column('target_team_id', sa.VARCHAR(), nullable=True))
    op.create_foreign_key(None, 'announcements', 'teams', ['target_team_id'], ['team_id'])
    op.drop_column('announcements', 'posted_at')
    op.drop_column('announcements', 'status')
    op.drop_column('announcements', 'requires_ack')
    op.drop_column('announcements', 'target_value')
    op.drop_index(op.f('ix_announcement_acks_id'), table_name='announcement_acks')
    op.alter_column('announcement_acks', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
