"""add calendar tables

Revision ID: 3dea157d44ad
Revises: 9254240a8e8f
Create Date: 2026-07-27 18:15:31.340449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dea157d44ad'
down_revision: Union[str, Sequence[str], None] = '378a25b35c89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_company_events_event_id'), 'company_events', ['event_id'], unique=False)
    op.create_table('holidays',
    sa.Column('holiday_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('holiday_id')
    )
    op.create_index(op.f('ix_holidays_holiday_id'), 'holidays', ['holiday_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_holidays_holiday_id'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_company_events_event_id'), table_name='company_events')
    op.drop_table('company_events')
    # ### end Alembic commands ###
