"""add purchase_date to asset

Revision ID: 4bb1f85e63cb
Revises: c24cf549cf95
Create Date: 2026-07-09 20:37:34.570200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb1f85e63cb'
down_revision: Union[str, Sequence[str], None] = 'c24cf549cf95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('purchase_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'purchase_date')
    # ### end Alembic commands ###
