"""add expected_days to onboarding tasks

Revision ID: 6af80a2cc0d9
Revises: cf227a12d0d2
Create Date: 2026-07-25 12:57:16.217560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6af80a2cc0d9'
down_revision: Union[str, Sequence[str], None] = 'cf227a12d0d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_tasks', sa.Column('expected_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onboarding_tasks', 'expected_days')
    # ### end Alembic commands ###
