"""Add attendance module

Revision ID: 75b1d17d2be2
Revises: 60d5c1c8f1e8
Create Date: 2026-07-13 19:44:13.301143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b1d17d2be2'
down_revision: Union[str, Sequence[str], None] = '60d5c1c8f1e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create attendance table
    op.create_table(
        'attendance',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('check_in', sa.DateTime(), nullable=True),
        sa.Column('check_out', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(50), nullable=False, server_default='present'),
        sa.Column('overtime_hours', sa.Float(), nullable=True, server_default='0.0'),
        sa.Column('remarks', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.UniqueConstraint('user_id', 'date', name='uq_attendance_user_date')
    )
    
    # Create indexes for attendance table
    op.create_index('idx_attendance_user_id', 'attendance', ['user_id'])
    op.create_index('idx_attendance_date', 'attendance', ['date'])
    op.create_index('idx_attendance_status', 'attendance', ['status'])
    
    # Create leave requests table
    op.create_table(
        'leave_requests',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('leave_type', sa.String(50), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=False),
        sa.Column('total_days', sa.Float(), nullable=False),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('status', sa.String(50), nullable=False, server_default='pending'),
        sa.Column('approved_by', sa.Integer(), nullable=True),
        sa.Column('approved_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL')
    )
    
    # Create indexes for leave_requests table
    op.create_index('idx_leaves_user_id', 'leave_requests', ['user_id'])
    op.create_index('idx_leaves_status', 'leave_requests', ['status'])
    op.create_index('idx_leaves_date_range', 'leave_requests', ['start_date', 'end_date'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes first
    op.drop_index('idx_leaves_date_range', table_name='leave_requests')
    op.drop_index('idx_leaves_status', table_name='leave_requests')
    op.drop_index('idx_leaves_user_id', table_name='leave_requests')
    
    op.drop_index('idx_attendance_status', table_name='attendance')
    op.drop_index('idx_attendance_date', table_name='attendance')
    op.drop_index('idx_attendance_user_id', table_name='attendance')
    
    # Drop tables
    op.drop_table('leave_requests')
    op.drop_table('attendance')
    # ### end Alembic commands ###