"""add M6 training tables

Revision ID: 7aea7544bf0a
Revises: c24cf549cf95
Create Date: 2026-07-09 12:29:04.801992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aea7544bf0a'
down_revision: Union[str, Sequence[str], None] = '60d5c1c8f1e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_programs',
    sa.Column('program_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('program_id')
    )
    op.create_table('training_enrollments',
    sa.Column('enrollment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['training_programs.program_id'], ),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    op.create_table('training_units',
    sa.Column('unit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['training_programs.program_id'], ),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_table('training_unit_completions',
    sa.Column('completion_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['training_enrollments.enrollment_id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['training_units.unit_id'], ),
    sa.PrimaryKeyConstraint('completion_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_unit_completions')
    op.drop_table('training_units')
    op.drop_table('training_enrollments')
    op.drop_table('training_programs')
    # ### end Alembic commands ###
