"""align field names to ER diagram, add Team and Onboarding templates

Revision ID: 99259f6424a5
Revises: 
Create Date: 2026-07-10 16:57:12.736909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99259f6424a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_templates',
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_index(op.f('ix_onboarding_templates_template_id'), 'onboarding_templates', ['template_id'], unique=False)
    op.create_table('teams',
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_index(op.f('ix_teams_team_id'), 'teams', ['team_id'], unique=False)
    op.create_table('employees',
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('manager_id', sa.String(), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=True),
    sa.Column('employment_status', sa.String(), nullable=False),
    sa.Column('access_tier', sa.String(), nullable=False),
    sa.Column('contact_details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=False)
    op.create_table('onboarding_tasks',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('responsible_role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['onboarding_templates.template_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_onboarding_tasks_task_id'), 'onboarding_tasks', ['task_id'], unique=False)
    op.create_table('employee_documents',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('retention_expiry', sa.Date(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_employee_documents_document_id'), 'employee_documents', ['document_id'], unique=False)
    op.create_table('onboarding_instances',
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['onboarding_templates.template_id'], ),
    sa.PrimaryKeyConstraint('instance_id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index(op.f('ix_onboarding_instances_instance_id'), 'onboarding_instances', ['instance_id'], unique=False)
    op.create_table('document_access_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('accessed_by', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['accessed_by'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['employee_documents.document_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('task_completions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('completed_by', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['onboarding_instances.instance_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['onboarding_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_completions')
    op.drop_table('document_access_logs')
    op.drop_index(op.f('ix_onboarding_instances_instance_id'), table_name='onboarding_instances')
    op.drop_table('onboarding_instances')
    op.drop_index(op.f('ix_employee_documents_document_id'), table_name='employee_documents')
    op.drop_table('employee_documents')
    op.drop_index(op.f('ix_onboarding_tasks_task_id'), table_name='onboarding_tasks')
    op.drop_table('onboarding_tasks')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_teams_team_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_onboarding_templates_template_id'), table_name='onboarding_templates')
    op.drop_table('onboarding_templates')
    # ### end Alembic commands ###
