"""initialize foundation tables m0 m5 m8

Revision ID: c24cf549cf95
Revises: 
Create Date: 2026-07-08 11:08:03.640410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24cf549cf95'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role_designation', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('reporting_manager_id', sa.String(), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=True),
    sa.Column('employment_status', sa.String(), nullable=False),
    sa.Column('access_tier', sa.String(), nullable=False),
    sa.Column('contact_details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['reporting_manager_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=False)
    op.create_table('employee_documents',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_employee_documents_document_id'), 'employee_documents', ['document_id'], unique=False)
    op.create_table('onboarding_instances',
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('completion_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('instance_id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index(op.f('ix_onboarding_instances_instance_id'), 'onboarding_instances', ['instance_id'], unique=False)
    op.create_table('document_access_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['employee_documents.document_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('onboarding_task_completions',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('responsible_party', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_by', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['onboarding_instances.instance_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_onboarding_task_completions_task_id'), 'onboarding_task_completions', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_task_completions_task_id'), table_name='onboarding_task_completions')
    op.drop_table('onboarding_task_completions')
    op.drop_table('document_access_logs')
    op.drop_index(op.f('ix_onboarding_instances_instance_id'), table_name='onboarding_instances')
    op.drop_table('onboarding_instances')
    op.drop_index(op.f('ix_employee_documents_document_id'), table_name='employee_documents')
    op.drop_table('employee_documents')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
