"""add required_doc_type to onboarding tasks

Revision ID: f10e48e3ff9f
Revises: 6af80a2cc0d9
Create Date: 2026-07-27 15:31:24.166233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f10e48e3ff9f'
down_revision: Union[str, Sequence[str], None] = '6af80a2cc0d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_tasks', sa.Column('required_doc_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onboarding_tasks', 'required_doc_type')
    # ### end Alembic commands ###
